[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_nft_anchor = "Abve8Cqe49EZjt3FihqkSQdEEtQioZ8T8DnZVg5fEbPh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/nacknime/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
